# Generated by Django 5.1.4 on 2025-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_id',
            field=models.CharField(default='<function uuid4 at 0x76b72411f7e0>', max_length=150),
        ),
    ]
