# Generated by Django 4.2 on 2025-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_fileupload_file_id_alter_fileupload_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_id',
            field=models.CharField(default='<function uuid4 at 0x00000182E0A14040>', max_length=150),
        ),
    ]
